import type { LibraryPreset } from './audioLibrary';
import type { TransitionPreset } from '../types';

// Generated by scripts/prepare-podcast-transitions.py; source recipes and hashes ship with the audio.
export const PODCAST_TRANSITIONS: LibraryPreset[] = [
  {
    "id": "sfx-transition-whoosh",
    "title": "Balayage rapide",
    "icon": "💨",
    "description": "Un souffle bref pour passer directement à la rubrique suivante.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "balayage rapide"
    ],
    "sourcePage": "https://lasonotheque.org/whoosh-4-s1796.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-whoosh.mp3",
    "duration": 0.39,
    "audioUrl": "audio/podcast-transitions/sfx-transition-whoosh.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-whoosh.mp3",
    "origin": "recording",
    "attribution": "Balayage rapide — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-cinematic",
    "title": "Balayage cinéma",
    "icon": "🎬",
    "description": "Un balayage ample avec un impact, pour une transition marquée.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "balayage cinéma"
    ],
    "sourcePage": "https://freesound.org/people/AudioPapkin/sounds/648729/",
    "author": "AudioPapkin",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-cinematic.mp3",
    "duration": 0.95,
    "audioUrl": "audio/podcast-transitions/sfx-transition-cinematic.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-cinematic.mp3",
    "origin": "recording",
    "attribution": "Balayage cinéma — AudioPapkin / Freesound — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-rise",
    "title": "Montée électronique",
    "icon": "↗️",
    "description": "Une montée synthétique pour annoncer la suite ou une révélation.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "montée électronique"
    ],
    "sourcePage": "https://freesound.org/people/Renovatio871/sounds/275762/",
    "author": "Renovatio871",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-rise.mp3",
    "duration": 3.61,
    "audioUrl": "audio/podcast-transitions/sfx-transition-rise.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-rise.mp3",
    "origin": "recording",
    "attribution": "Montée électronique — Renovatio871 / Freesound — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-fade",
    "title": "Signature lumineuse",
    "icon": "🎹",
    "description": "Une ponctuation mélodique pour ouvrir une nouvelle rubrique.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "signature lumineuse"
    ],
    "sourcePage": "https://freesound.org/people/TMPZ_1/sounds/442680/",
    "author": "TMPZ_1",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-fade.mp3",
    "duration": 3.43,
    "audioUrl": "audio/podcast-transitions/sfx-transition-fade.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-fade.mp3",
    "origin": "recording",
    "attribution": "Signature lumineuse — TMPZ_1 / Freesound — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-radio",
    "title": "Zapping radio",
    "icon": "📻",
    "description": "Un changement de station pour relancer un reportage.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "zapping radio"
    ],
    "sourcePage": "https://lasonotheque.org/radio-balayage-frequences-2-s2618.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-radio.mp3",
    "duration": 1.8,
    "audioUrl": "audio/podcast-transitions/sfx-transition-radio.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-radio.mp3",
    "origin": "recording",
    "attribution": "Zapping radio — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-radio-analog",
    "title": "Zapping radio · tuner analogique",
    "icon": "📻",
    "description": "Un balayage continu du tuner, avec grésillements et passages de stations.",
    "tags": [
      "transition",
      "radio",
      "zapping",
      "tuner",
      "balayage"
    ],
    "sourcePage": "https://lasonotheque.org/radio-balayage-frequences-1-s2617.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-radio-analog.mp3",
    "duration": 6.23,
    "audioUrl": "audio/podcast-transitions/sfx-transition-radio-analog.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-radio-analog.mp3",
    "origin": "recording",
    "attribution": "Zapping radio · tuner analogique — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-radio-scan",
    "title": "Zapping radio · recherche de station",
    "icon": "📻",
    "description": "Une recherche de station plus longue, avec plusieurs changements de fréquence.",
    "tags": [
      "transition",
      "radio",
      "zapping",
      "tuner",
      "balayage"
    ],
    "sourcePage": "https://lasonotheque.org/radio-balayage-frequences-3-s2619.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-radio-scan.mp3",
    "duration": 7.89,
    "audioUrl": "audio/podcast-transitions/sfx-transition-radio-scan.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-radio-scan.mp3",
    "origin": "recording",
    "attribution": "Zapping radio · recherche de station — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-radio-fm",
    "title": "Zapping radio · traversée FM",
    "icon": "📻",
    "description": "Une traversée de la bande FM pour passer à une nouvelle séquence.",
    "tags": [
      "transition",
      "radio",
      "zapping",
      "tuner",
      "balayage"
    ],
    "sourcePage": "https://freesound.org/people/davidbain/sounds/259706/",
    "author": "davidbain",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-radio-fm.mp3",
    "duration": 6.5,
    "audioUrl": "audio/podcast-transitions/sfx-transition-radio-fm.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-radio-fm.mp3",
    "origin": "recording",
    "attribution": "Zapping radio · traversée FM — davidbain / Freesound — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-impact",
    "title": "Impact de rubrique",
    "icon": "💥",
    "description": "Un accent grave et net pour marquer un changement de sujet.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "impact de rubrique"
    ],
    "sourcePage": "https://freesound.org/people/qubodup/sounds/222517/",
    "author": "qubodup",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-impact.mp3",
    "duration": 3.2,
    "audioUrl": "audio/podcast-transitions/sfx-transition-impact.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-impact.mp3",
    "origin": "recording",
    "attribution": "Impact de rubrique — qubodup / Freesound — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-portal",
    "title": "Ta-da !",
    "icon": "🎺",
    "description": "Une courte fanfare pour annoncer une découverte ou un résultat.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "ta-da !"
    ],
    "sourcePage": "https://freesound.org/people/plasterbrain/sounds/397355/",
    "author": "plasterbrain",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-portal.mp3",
    "duration": 1.51,
    "audioUrl": "audio/podcast-transitions/sfx-transition-portal.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-portal.mp3",
    "origin": "recording",
    "attribution": "Ta-da ! — plasterbrain / Freesound — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-sparkle",
    "title": "Carillon scintillant",
    "icon": "✨",
    "description": "Des notes cristallines pour une transition légère.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "carillon scintillant"
    ],
    "sourcePage": "https://lasonotheque.org/chimes-reve-8-s2086.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-sparkle.mp3",
    "duration": 2.04,
    "audioUrl": "audio/podcast-transitions/sfx-transition-sparkle.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-sparkle.mp3",
    "origin": "recording",
    "attribution": "Carillon scintillant — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-mystery",
    "title": "Ping mystérieux",
    "icon": "📡",
    "description": "Une note résonnante pour introduire une question ou une enquête.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "ping mystérieux"
    ],
    "sourcePage": "https://lasonotheque.org/sonar-2-s1920.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-mystery.mp3",
    "duration": 2.23,
    "audioUrl": "audio/podcast-transitions/sfx-transition-mystery.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-mystery.mp3",
    "origin": "recording",
    "attribution": "Ping mystérieux — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-question",
    "title": "Roulement d’annonce",
    "icon": "🥁",
    "description": "Un roulement de tambour avant une réponse ou un résultat.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "roulement d’annonce"
    ],
    "sourcePage": "https://lasonotheque.org/roulement-de-tambour-1-s-s2400.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-question.mp3",
    "duration": 2.4,
    "audioUrl": "audio/podcast-transitions/sfx-transition-question.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-question.mp3",
    "origin": "recording",
    "attribution": "Roulement d’annonce — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-drop",
    "title": "Scratch vinyle",
    "icon": "💿",
    "description": "Un arrêt de disque pour une rupture, une surprise ou un retour en arrière.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "scratch vinyle"
    ],
    "sourcePage": "https://lasonotheque.org/scratch-vinyle-18-s2875.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-drop.mp3",
    "duration": 0.69,
    "audioUrl": "audio/podcast-transitions/sfx-transition-drop.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-drop.mp3",
    "origin": "recording",
    "attribution": "Scratch vinyle — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-failure",
    "title": "Buzzer de quiz",
    "icon": "🚫",
    "description": "Un signal clair pour une réponse fausse ou une contradiction.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "buzzer de quiz"
    ],
    "sourcePage": "https://lasonotheque.org/buzzer-4-s1586.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-failure.mp3",
    "duration": 0.9612,
    "audioUrl": "audio/podcast-transitions/sfx-transition-failure.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-failure.mp3",
    "origin": "recording",
    "attribution": "Buzzer de quiz — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-bell",
    "title": "Ba-dum-tss !",
    "icon": "😄",
    "description": "Une ponctuation de batterie après une blague.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "ba-dum-tss !"
    ],
    "sourcePage": "https://lasonotheque.org/batterie-de-blague-3-s2410.html",
    "author": "Joseph SARDIN",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-bell.mp3",
    "duration": 2.15,
    "audioUrl": "audio/podcast-transitions/sfx-transition-bell.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-bell.mp3",
    "origin": "recording",
    "attribution": "Ba-dum-tss ! — Joseph SARDIN / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  },
  {
    "id": "sfx-transition-page",
    "title": "Page tournée",
    "icon": "📖",
    "description": "Un froissement de page pour changer de chapitre ou poursuivre un récit.",
    "tags": [
      "transition",
      "podcast",
      "radio",
      "page tournée"
    ],
    "sourcePage": "https://lasonotheque.org/page-qui-tourne-s0164.html",
    "author": "DavidGreck",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "kind": "sfx",
    "category": "Transitions et ponctuation",
    "soundGroup": "effect",
    "filename": "sfx-transition-page.mp3",
    "duration": 0.45,
    "audioUrl": "audio/podcast-transitions/sfx-transition-page.mp3",
    "fallbackUrl": "audio/podcast-transitions/sfx-transition-page.mp3",
    "origin": "recording",
    "attribution": "Page tournée — DavidGreck / LaSonothèque — CC0. Extrait court, silences retirés, niveau harmonisé, fondus de 5/65 ms, MP3 stéréo 192 kbit/s."
  }
];

export const TRANSITION_RECORDINGS: { preset: TransitionPreset; libraryId: string; label: string; icon: string; description: string }[] = [
  {
    "preset": "whoosh",
    "libraryId": "sfx-transition-whoosh",
    "label": "Balayage rapide",
    "icon": "💨",
    "description": "Un souffle bref pour passer directement à la rubrique suivante."
  },
  {
    "preset": "cinematic",
    "libraryId": "sfx-transition-cinematic",
    "label": "Balayage cinéma",
    "icon": "🎬",
    "description": "Un balayage ample avec un impact, pour une transition marquée."
  },
  {
    "preset": "rise",
    "libraryId": "sfx-transition-rise",
    "label": "Montée électronique",
    "icon": "↗️",
    "description": "Une montée synthétique pour annoncer la suite ou une révélation."
  },
  {
    "preset": "fade",
    "libraryId": "sfx-transition-fade",
    "label": "Signature lumineuse",
    "icon": "🎹",
    "description": "Une ponctuation mélodique pour ouvrir une nouvelle rubrique."
  },
  {
    "preset": "radio",
    "libraryId": "sfx-transition-radio",
    "label": "Zapping radio",
    "icon": "📻",
    "description": "Un changement de station pour relancer un reportage."
  },
  {
    "preset": "radio",
    "libraryId": "sfx-transition-radio-analog",
    "label": "Zapping radio · tuner analogique",
    "icon": "📻",
    "description": "Un balayage continu du tuner, avec grésillements et passages de stations."
  },
  {
    "preset": "radio",
    "libraryId": "sfx-transition-radio-scan",
    "label": "Zapping radio · recherche de station",
    "icon": "📻",
    "description": "Une recherche de station plus longue, avec plusieurs changements de fréquence."
  },
  {
    "preset": "radio",
    "libraryId": "sfx-transition-radio-fm",
    "label": "Zapping radio · traversée FM",
    "icon": "📻",
    "description": "Une traversée de la bande FM pour passer à une nouvelle séquence."
  },
  {
    "preset": "impact",
    "libraryId": "sfx-transition-impact",
    "label": "Impact de rubrique",
    "icon": "💥",
    "description": "Un accent grave et net pour marquer un changement de sujet."
  },
  {
    "preset": "portal",
    "libraryId": "sfx-transition-portal",
    "label": "Ta-da !",
    "icon": "🎺",
    "description": "Une courte fanfare pour annoncer une découverte ou un résultat."
  },
  {
    "preset": "sparkle",
    "libraryId": "sfx-transition-sparkle",
    "label": "Carillon scintillant",
    "icon": "✨",
    "description": "Des notes cristallines pour une transition légère."
  },
  {
    "preset": "mystery",
    "libraryId": "sfx-transition-mystery",
    "label": "Ping mystérieux",
    "icon": "📡",
    "description": "Une note résonnante pour introduire une question ou une enquête."
  },
  {
    "preset": "question",
    "libraryId": "sfx-transition-question",
    "label": "Roulement d’annonce",
    "icon": "🥁",
    "description": "Un roulement de tambour avant une réponse ou un résultat."
  },
  {
    "preset": "drop",
    "libraryId": "sfx-transition-drop",
    "label": "Scratch vinyle",
    "icon": "💿",
    "description": "Un arrêt de disque pour une rupture, une surprise ou un retour en arrière."
  },
  {
    "preset": "failure",
    "libraryId": "sfx-transition-failure",
    "label": "Buzzer de quiz",
    "icon": "🚫",
    "description": "Un signal clair pour une réponse fausse ou une contradiction."
  },
  {
    "preset": "bell",
    "libraryId": "sfx-transition-bell",
    "label": "Ba-dum-tss !",
    "icon": "😄",
    "description": "Une ponctuation de batterie après une blague."
  },
  {
    "preset": "page",
    "libraryId": "sfx-transition-page",
    "label": "Page tournée",
    "icon": "📖",
    "description": "Un froissement de page pour changer de chapitre ou poursuivre un récit."
  }
];
